/**
 *  "TRMSim-WSN, Trust and Reputation Models Simulator for Wireless
 * Sensor Networks" is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version always keeping
 * the additional terms specified in this license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 *
 * Additional Terms of this License
 * --------------------------------
 *
 * 1. It is Required the preservation of specified reasonable legal notices
 *   and author attributions in that material and in the Appropriate Legal
 *   Notices displayed by works containing it.
 *
 * 2. It is limited the use for publicity purposes of names of licensors or
 *   authors of the material.
 *
 * 3. It is Required indemnification of licensors and authors of that material
 *   by anyone who conveys the material (or modified versions of it) with
 *   contractual assumptions of liability to the recipient, for any liability
 *   that these contractual assumptions directly impose on those licensors
 *   and authors.
 *
 * 4. It is Prohibited misrepresentation of the origin of that material, and it is
 *   required that modified versions of such material be marked in reasonable
 *   ways as different from the original version.
 *
 * 5. It is Declined to grant rights under trademark law for use of some trade
 *   names, trademarks, or service marks.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (lgpl.txt).  If not, see <http://www.gnu.org/licenses/>
*/

package es.ants.felixgm.trmsim_wsn.gui;

import java.awt.Color;
import java.awt.Graphics;

/**
 * <p>This class represents the generic legend of colors for plotting a network</p>
 * @author <a href="http://ants.dif.um.es/~felixgm/en" target="_blank">F&eacute;lix G&oacute;mez M&aacute;rmol</a>, <a href="http://webs.um.es/gregorio" target="_blank">Gregorio Mart&iacute;nez P&eacute;rez</a>
 * @version 0.4
 * @since 0.4
 */
public class LegendPanel extends javax.swing.JPanel {

    protected Color backgroundColor = Color.WHITE;
    protected Color charactersColor = Color.BLACK;
    protected Color clientColor = Color.ORANGE;
    protected Color benevolentServerColor = Color.GREEN;
    protected Color maliciousServerColor = Color.RED;
    protected Color relayServerColor = Color.BLUE;
    protected Color idleNodeColor = Color.BLACK;

    /** Creates new form LegendPanel */
    public LegendPanel() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics graphics) {
        super.paintComponent(graphics);
        plotLegend(graphics);
    }

    public void plotLegend() {
        plotLegend(this.getGraphics());
    }

    protected void plotLegend(Graphics graphics) {
        int height = this.getHeight();
        int width = this.getWidth();

        graphics.setColor(backgroundColor);
        graphics.fillRect(0, 0, width, height);

        graphics.setColor(clientColor);
        graphics.fillArc(5, (int)(height*(1.0/7.0))-5, 10, 10, 0, 360);
        graphics.setColor(benevolentServerColor);
        graphics.fillArc(5, (int)(height*(2.0/7.0))-5, 10, 10, 0, 360);
        graphics.setColor(maliciousServerColor);
        graphics.fillArc(5, (int)(height*(3.0/7.0))-5, 10, 10, 0, 360);
        graphics.setColor(relayServerColor);
        graphics.fillArc(5, (int)(height*(4.0/7.0))-5, 10, 10, 0, 360);
        graphics.setColor(idleNodeColor);
        graphics.fillArc(5, (int)(height*(5.0/7.0))-5, 10, 10, 0, 360);

        graphics.setColor(charactersColor);
        graphics.drawString("Client",20,(int)(height*(1.0/7.0))+5);
        graphics.drawString("Benevolent",20,(int)(height*(2.0/7.0))+5);
        graphics.drawString("Malicious",20,(int)(height*(3.0/7.0))+5);
        graphics.drawString("Relay",20,(int)(height*(4.0/7.0))+5);
        graphics.drawString("Idle",20,(int)(height*(5.0/7.0))+5);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
