/**
 *  "TRMSim-WSN, Trust and Reputation Models Simulator for Wireless
 * Sensor Networks" is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version always keeping
 * the additional terms specified in this license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 *
 * Additional Terms of this License
 * --------------------------------
 *
 * 1. It is Required the preservation of specified reasonable legal notices
 *   and author attributions in that material and in the Appropriate Legal
 *   Notices displayed by works containing it.
 *
 * 2. It is limited the use for publicity purposes of names of licensors or
 *   authors of the material.
 *
 * 3. It is Required indemnification of licensors and authors of that material
 *   by anyone who conveys the material (or modified versions of it) with
 *   contractual assumptions of liability to the recipient, for any liability
 *   that these contractual assumptions directly impose on those licensors
 *   and authors.
 *
 * 4. It is Prohibited misrepresentation of the origin of that material, and it is
 *   required that modified versions of such material be marked in reasonable
 *   ways as different from the original version.
 *
 * 5. It is Declined to grant rights under trademark law for use of some trade
 *   names, trademarks, or service marks.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (lgpl.txt).  If not, see <http://www.gnu.org/licenses/>
*/

package es.ants.felixgm.trmsim_wsn.gui.parameterpanels;

import es.ants.felixgm.trmsim_wsn.trm.TRMParameters;
import es.ants.felixgm.trmsim_wsn.trm.lftm.LFTM_Parameters;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.DefuzzifierCenterOfGravity;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.FuzzySetPanel;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.LinguisticTerm;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.MembershipFunctionTrapezoidal;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.MembershipFunctionTriangular;
import java.util.Collection;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JTextField;

/**
 * <p>This class represents the panel used to retrieve the parameters of LFTM</p>
 * @author <a href="http://ants.dif.um.es/~felixgm/en" target="_blank">F&eacute;lix G&oacute;mez M&aacute;rmol</a>, <a href="http://webs.um.es/gregorio" target="_blank">Gregorio Mart&iacute;nez P&eacute;rez</a>
 * @version 0.5
 * @since 0.4
 */
public class LFTM_ParametersPanel extends TRMParametersPanel {

    protected Vector<DefaultComboBoxModel> membershipFunctionsComboBoxModels;
    protected InputVerifier doubleInputVerifier;
    protected FuzzySetPanel fuzzySetPanelAux, fuzzySetPanel;

    /** Creates new form LFTM_ParametersPanel */
    public LFTM_ParametersPanel() {
        membershipFunctionsComboBoxModels = new Vector<DefaultComboBoxModel>();
        for (int i = 0; i < 5; i++) {
            membershipFunctionsComboBoxModels.add(new DefaultComboBoxModel());
            membershipFunctionsComboBoxModels.lastElement().addElement("Trapezoidal");
            membershipFunctionsComboBoxModels.lastElement().addElement("Triangular");
        }
        doubleInputVerifier = new InputVerifier() {
            public boolean verify(JComponent input) {
                try {
                   JTextField textField = (JTextField) input;
                   Double.parseDouble(textField.getText());
                   return true;
                } catch (Exception ex) {
                    return false;
                }
            }
        };

        fuzzySetPanelAux = new FuzzySetPanel();
        fuzzySetPanel = new FuzzySetPanel();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lftm_ParametersPanelTabbedPane = new javax.swing.JTabbedPane();
        btrm_ParametersPanel = new javax.swing.JPanel();
        phiLabel = new javax.swing.JLabel();
        phiSlider = new javax.swing.JSlider();
        rhoLabel = new javax.swing.JLabel();
        rhoSlider = new javax.swing.JSlider();
        q0Label = new javax.swing.JLabel();
        q0Slider = new javax.swing.JSlider();
        numAntsLabel = new javax.swing.JLabel();
        numAntsSlider = new javax.swing.JSlider();
        numIterationsLabel = new javax.swing.JLabel();
        numIterationsSlider = new javax.swing.JSlider();
        numIterationsTextField = new javax.swing.JTextField();
        numAntsTextField = new javax.swing.JTextField();
        q0TextField = new javax.swing.JTextField();
        rhoTextField = new javax.swing.JTextField();
        phiTextField = new javax.swing.JTextField();
        alphaLabel = new javax.swing.JLabel();
        alphaSlider = new javax.swing.JSlider();
        alphaTextField = new javax.swing.JTextField();
        betaLabel = new javax.swing.JLabel();
        betaSlider = new javax.swing.JSlider();
        betaTextField = new javax.swing.JTextField();
        initialPheromoneLabel = new javax.swing.JLabel();
        initialPheromoneSlider = new javax.swing.JSlider();
        initialPheromoneTextField = new javax.swing.JTextField();
        punishmentThresholdLabel = new javax.swing.JLabel();
        punishmentThresholdSlider = new javax.swing.JSlider();
        punishmentThresholdTextField = new javax.swing.JTextField();
        pathLengthFactorLabel = new javax.swing.JLabel();
        pathLengthFactorSlider = new javax.swing.JSlider();
        pathLengthFactorTextField = new javax.swing.JTextField();
        transitionThresholdLabel = new javax.swing.JLabel();
        transitionThresholdSlider = new javax.swing.JSlider();
        transitionThresholdTextField = new javax.swing.JTextField();
        linguisticTermsPanel = new javax.swing.JPanel();
        veryHighLabel = new javax.swing.JLabel();
        highLabel = new javax.swing.JLabel();
        mediumLabel = new javax.swing.JLabel();
        lowLabel = new javax.swing.JLabel();
        veryLowLabel = new javax.swing.JLabel();
        veryHighMembershipFunctionComboBox = new javax.swing.JComboBox();
        membershipFunctionLabel = new javax.swing.JLabel();
        highMembershipFunctionComboBox = new javax.swing.JComboBox();
        mediumMembershipFunctionComboBox = new javax.swing.JComboBox();
        lowMembershipFunctionComboBox = new javax.swing.JComboBox();
        veryLowMembershipFunctionComboBox = new javax.swing.JComboBox();
        veryHighAParameterTextField = new javax.swing.JTextField();
        veryHighBParameterTextField = new javax.swing.JTextField();
        veryHighCParameterTextField = new javax.swing.JTextField();
        veryHighDParameterTextField = new javax.swing.JTextField();
        aParameterLabel = new javax.swing.JLabel();
        bParameterLabel = new javax.swing.JLabel();
        cParameterLabel = new javax.swing.JLabel();
        dParameterLabel = new javax.swing.JLabel();
        highAParameterTextField = new javax.swing.JTextField();
        highBParameterTextField = new javax.swing.JTextField();
        highCParameterTextField = new javax.swing.JTextField();
        highDParameterTextField = new javax.swing.JTextField();
        mediumDParameterTextField = new javax.swing.JTextField();
        mediumCParameterTextField = new javax.swing.JTextField();
        mediumBParameterTextField = new javax.swing.JTextField();
        mediumAParameterTextField = new javax.swing.JTextField();
        lowAParameterTextField = new javax.swing.JTextField();
        lowCParameterTextField = new javax.swing.JTextField();
        lowDParameterTextField = new javax.swing.JTextField();
        lowBParameterTextField = new javax.swing.JTextField();
        veryLowDParameterTextField = new javax.swing.JTextField();
        veryLowCParameterTextField = new javax.swing.JTextField();
        veryLowBParameterTextField = new javax.swing.JTextField();
        veryLowAParameterTextField = new javax.swing.JTextField();
        universeMINLabel = new javax.swing.JLabel();
        universeMAXLabel = new javax.swing.JLabel();
        universeMINTextField = new javax.swing.JTextField();
        universeMAXTextField = new javax.swing.JTextField();
        linguisticTermsPanelContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(450, 500));

        lftm_ParametersPanelTabbedPane.setPreferredSize(new java.awt.Dimension(450, 500));

        phiLabel.setText("phi");
        phiLabel.setEnabled(false);

        phiSlider.setMaximum(10000);
        phiSlider.setValue(1784);
        phiSlider.setEnabled(false);
        phiSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        phiSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                phiSliderStateChanged(evt);
            }
        });

        rhoLabel.setText("rho");
        rhoLabel.setEnabled(false);

        rhoSlider.setMaximum(10000);
        rhoSlider.setValue(3044);
        rhoSlider.setEnabled(false);
        rhoSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        rhoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rhoSliderStateChanged(evt);
            }
        });

        q0Label.setText("q0");
        q0Label.setEnabled(false);

        q0Slider.setMaximum(10000);
        q0Slider.setValue(8331);
        q0Slider.setEnabled(false);
        q0Slider.setPreferredSize(new java.awt.Dimension(140, 25));
        q0Slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                q0SliderStateChanged(evt);
            }
        });

        numAntsLabel.setText("Num ants");
        numAntsLabel.setEnabled(false);

        numAntsSlider.setMaximum(10000);
        numAntsSlider.setValue(3973);
        numAntsSlider.setEnabled(false);
        numAntsSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        numAntsSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numAntsSliderStateChanged(evt);
            }
        });

        numIterationsLabel.setText("Num iterations");
        numIterationsLabel.setEnabled(false);

        numIterationsSlider.setMaximum(10000);
        numIterationsSlider.setValue(5404);
        numIterationsSlider.setEnabled(false);
        numIterationsSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        numIterationsSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numIterationsSliderStateChanged(evt);
            }
        });

        numIterationsTextField.setEditable(false);
        numIterationsTextField.setText("0.5404");
        numIterationsTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        numAntsTextField.setEditable(false);
        numAntsTextField.setText("0.3973");
        numAntsTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        q0TextField.setEditable(false);
        q0TextField.setText("0.8331");
        q0TextField.setPreferredSize(new java.awt.Dimension(45, 25));

        rhoTextField.setEditable(false);
        rhoTextField.setText("0.3044");
        rhoTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        phiTextField.setEditable(false);
        phiTextField.setText("0.1784");
        phiTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        alphaLabel.setText("alpha");
        alphaLabel.setEnabled(false);

        alphaSlider.setMaximum(10000);
        alphaSlider.setValue(10000);
        alphaSlider.setEnabled(false);
        alphaSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        alphaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alphaSliderStateChanged(evt);
            }
        });

        alphaTextField.setEditable(false);
        alphaTextField.setText("1.0");
        alphaTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        betaLabel.setText("beta");
        betaLabel.setEnabled(false);

        betaSlider.setMaximum(10000);
        betaSlider.setValue(10000);
        betaSlider.setEnabled(false);
        betaSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        betaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                betaSliderStateChanged(evt);
            }
        });

        betaTextField.setEditable(false);
        betaTextField.setText("1.0");
        betaTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        initialPheromoneLabel.setText("Initial pheromone");
        initialPheromoneLabel.setEnabled(false);

        initialPheromoneSlider.setMaximum(10000);
        initialPheromoneSlider.setValue(4928);
        initialPheromoneSlider.setEnabled(false);
        initialPheromoneSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        initialPheromoneSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                initialPheromoneSliderStateChanged(evt);
            }
        });

        initialPheromoneTextField.setEditable(false);
        initialPheromoneTextField.setText("0.4928");
        initialPheromoneTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        punishmentThresholdLabel.setText("Punishment threshold");
        punishmentThresholdLabel.setEnabled(false);

        punishmentThresholdSlider.setMaximum(10000);
        punishmentThresholdSlider.setValue(6806);
        punishmentThresholdSlider.setEnabled(false);
        punishmentThresholdSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        punishmentThresholdSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                punishmentThresholdSliderStateChanged(evt);
            }
        });

        punishmentThresholdTextField.setEditable(false);
        punishmentThresholdTextField.setText("0.6806");
        punishmentThresholdTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        pathLengthFactorLabel.setText("Path length factor");
        pathLengthFactorLabel.setEnabled(false);

        pathLengthFactorSlider.setMaximum(10000);
        pathLengthFactorSlider.setValue(5651);
        pathLengthFactorSlider.setEnabled(false);
        pathLengthFactorSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        pathLengthFactorSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pathLengthFactorSliderStateChanged(evt);
            }
        });

        pathLengthFactorTextField.setEditable(false);
        pathLengthFactorTextField.setText("0.5651");
        pathLengthFactorTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        transitionThresholdLabel.setText("Transition threshold");
        transitionThresholdLabel.setEnabled(false);

        transitionThresholdSlider.setMaximum(10000);
        transitionThresholdSlider.setValue(4972);
        transitionThresholdSlider.setEnabled(false);
        transitionThresholdSlider.setPreferredSize(new java.awt.Dimension(140, 25));
        transitionThresholdSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                transitionThresholdSliderStateChanged(evt);
            }
        });

        transitionThresholdTextField.setEditable(false);
        transitionThresholdTextField.setText("0.4972");
        transitionThresholdTextField.setPreferredSize(new java.awt.Dimension(45, 25));

        javax.swing.GroupLayout btrm_ParametersPanelLayout = new javax.swing.GroupLayout(btrm_ParametersPanel);
        btrm_ParametersPanel.setLayout(btrm_ParametersPanelLayout);
        btrm_ParametersPanelLayout.setHorizontalGroup(
            btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numIterationsLabel)
                    .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                        .addComponent(numIterationsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numIterationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numAntsLabel)
                    .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                        .addComponent(numAntsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numAntsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phiSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rhoLabel)
                            .addComponent(rhoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(phiLabel)
                    .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                        .addComponent(q0Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(q0Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                            .addComponent(betaLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btrm_ParametersPanelLayout.createSequentialGroup()
                            .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(initialPheromoneLabel)
                                .addComponent(pathLengthFactorLabel)
                                .addComponent(punishmentThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(transitionThresholdLabel)
                                .addComponent(pathLengthFactorSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(betaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alphaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(initialPheromoneSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(transitionThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(punishmentThresholdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(12, 12, 12)
                            .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(alphaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pathLengthFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(punishmentThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(betaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(transitionThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(initialPheromoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(alphaLabel))
                .addGap(192, 192, 192))
        );
        btrm_ParametersPanelLayout.setVerticalGroup(
            btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                                .addComponent(phiLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phiSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(phiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(rhoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rhoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rhoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q0Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q0Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numAntsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numAntsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numAntsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numIterationsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numIterationsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numIterationsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btrm_ParametersPanelLayout.createSequentialGroup()
                        .addComponent(alphaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alphaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alphaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(betaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(betaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(betaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initialPheromoneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(initialPheromoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(initialPheromoneSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(punishmentThresholdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(punishmentThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(punishmentThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathLengthFactorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pathLengthFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pathLengthFactorSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transitionThresholdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btrm_ParametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transitionThresholdSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transitionThresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
        );

        lftm_ParametersPanelTabbedPane.addTab("BTRM", btrm_ParametersPanel);

        veryHighLabel.setText("Very High");
        veryHighLabel.setEnabled(false);

        highLabel.setText("High");
        highLabel.setEnabled(false);

        mediumLabel.setText("Medium");
        mediumLabel.setEnabled(false);

        lowLabel.setText("Low");
        lowLabel.setEnabled(false);

        veryLowLabel.setText("Very Low");
        veryLowLabel.setEnabled(false);

        veryHighMembershipFunctionComboBox.setModel(membershipFunctionsComboBoxModels.get(0));
        veryHighMembershipFunctionComboBox.setEnabled(false);
        veryHighMembershipFunctionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                veryHighMembershipFunctionComboBoxItemStateChanged(evt);
            }
        });

        membershipFunctionLabel.setText("Membership function");
        membershipFunctionLabel.setEnabled(false);

        highMembershipFunctionComboBox.setModel(membershipFunctionsComboBoxModels.get(1));
        highMembershipFunctionComboBox.setEnabled(false);
        highMembershipFunctionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                highMembershipFunctionComboBoxItemStateChanged(evt);
            }
        });

        mediumMembershipFunctionComboBox.setModel(membershipFunctionsComboBoxModels.get(2));
        mediumMembershipFunctionComboBox.setEnabled(false);
        mediumMembershipFunctionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mediumMembershipFunctionComboBoxItemStateChanged(evt);
            }
        });

        lowMembershipFunctionComboBox.setModel(membershipFunctionsComboBoxModels.get(3));
        lowMembershipFunctionComboBox.setEnabled(false);
        lowMembershipFunctionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lowMembershipFunctionComboBoxItemStateChanged(evt);
            }
        });

        veryLowMembershipFunctionComboBox.setModel(membershipFunctionsComboBoxModels.get(4));
        veryLowMembershipFunctionComboBox.setEnabled(false);
        veryLowMembershipFunctionComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                veryLowMembershipFunctionComboBoxItemStateChanged(evt);
            }
        });

        veryHighAParameterTextField.setEnabled(false);
        veryHighAParameterTextField.setInputVerifier(doubleInputVerifier);

        veryHighBParameterTextField.setEnabled(false);
        veryHighBParameterTextField.setInputVerifier(doubleInputVerifier);

        veryHighCParameterTextField.setEnabled(false);
        veryHighCParameterTextField.setInputVerifier(doubleInputVerifier);

        veryHighDParameterTextField.setEnabled(false);
        veryHighDParameterTextField.setInputVerifier(doubleInputVerifier);

        aParameterLabel.setText("a");
        aParameterLabel.setEnabled(false);

        bParameterLabel.setText("b");
        bParameterLabel.setEnabled(false);

        cParameterLabel.setText("c");
        cParameterLabel.setEnabled(false);

        dParameterLabel.setText("d");
        dParameterLabel.setEnabled(false);

        highAParameterTextField.setEnabled(false);
        highAParameterTextField.setInputVerifier(doubleInputVerifier);

        highBParameterTextField.setEnabled(false);
        highBParameterTextField.setInputVerifier(doubleInputVerifier);

        highCParameterTextField.setEnabled(false);
        highCParameterTextField.setInputVerifier(doubleInputVerifier);

        highDParameterTextField.setEnabled(false);
        highDParameterTextField.setInputVerifier(doubleInputVerifier);

        mediumDParameterTextField.setEnabled(false);
        mediumDParameterTextField.setInputVerifier(doubleInputVerifier);

        mediumCParameterTextField.setEnabled(false);
        mediumCParameterTextField.setInputVerifier(doubleInputVerifier);

        mediumBParameterTextField.setEnabled(false);
        mediumBParameterTextField.setInputVerifier(doubleInputVerifier);

        mediumAParameterTextField.setEnabled(false);
        mediumAParameterTextField.setInputVerifier(doubleInputVerifier);

        lowAParameterTextField.setEnabled(false);
        lowAParameterTextField.setInputVerifier(doubleInputVerifier);

        lowCParameterTextField.setEnabled(false);
        lowCParameterTextField.setInputVerifier(doubleInputVerifier);

        lowDParameterTextField.setEnabled(false);
        lowDParameterTextField.setInputVerifier(doubleInputVerifier);

        lowBParameterTextField.setEnabled(false);
        lowBParameterTextField.setInputVerifier(doubleInputVerifier);

        veryLowDParameterTextField.setEnabled(false);
        veryLowDParameterTextField.setInputVerifier(doubleInputVerifier);

        veryLowCParameterTextField.setEnabled(false);
        veryLowCParameterTextField.setInputVerifier(doubleInputVerifier);

        veryLowBParameterTextField.setEnabled(false);
        veryLowBParameterTextField.setInputVerifier(doubleInputVerifier);

        veryLowAParameterTextField.setEnabled(false);
        veryLowAParameterTextField.setInputVerifier(doubleInputVerifier);

        universeMINLabel.setText("Universe MIN");
        universeMINLabel.setEnabled(false);

        universeMAXLabel.setText("Universe MAX");
        universeMAXLabel.setEnabled(false);

        universeMINTextField.setText("0.0");
        universeMINTextField.setEnabled(false);

        universeMAXTextField.setText("1.0");
        universeMAXTextField.setEnabled(false);

        linguisticTermsPanelContainer.add(fuzzySetPanelAux,null);
        linguisticTermsPanelContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout linguisticTermsPanelContainerLayout = new javax.swing.GroupLayout(linguisticTermsPanelContainer);
        linguisticTermsPanelContainer.setLayout(linguisticTermsPanelContainerLayout);
        linguisticTermsPanelContainerLayout.setHorizontalGroup(
            linguisticTermsPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        linguisticTermsPanelContainerLayout.setVerticalGroup(
            linguisticTermsPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout linguisticTermsPanelLayout = new javax.swing.GroupLayout(linguisticTermsPanel);
        linguisticTermsPanel.setLayout(linguisticTermsPanelLayout);
        linguisticTermsPanelLayout.setHorizontalGroup(
            linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(veryLowLabel)
                            .addComponent(lowLabel)
                            .addComponent(mediumLabel)
                            .addComponent(highLabel)
                            .addComponent(veryHighLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(highMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(membershipFunctionLabel)
                                        .addComponent(veryHighMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lowMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mediumMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                                        .addComponent(lowAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lowBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lowCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lowDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                                        .addComponent(mediumAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mediumBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mediumCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mediumDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(veryHighAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(aParameterLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(veryHighBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bParameterLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(veryHighCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cParameterLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dParameterLabel)
                                            .addComponent(veryHighDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                                        .addComponent(highAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(highBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(highCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(highDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                                .addComponent(veryLowMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(veryLowAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(veryLowBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(veryLowCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(veryLowDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, linguisticTermsPanelLayout.createSequentialGroup()
                                .addComponent(universeMINLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(universeMINTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, linguisticTermsPanelLayout.createSequentialGroup()
                                .addComponent(universeMAXLabel)
                                .addGap(18, 18, 18)
                                .addComponent(universeMAXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(linguisticTermsPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        linguisticTermsPanelLayout.setVerticalGroup(
            linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membershipFunctionLabel)
                    .addComponent(aParameterLabel)
                    .addComponent(bParameterLabel)
                    .addComponent(cParameterLabel)
                    .addComponent(dParameterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veryHighMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryHighLabel)
                    .addComponent(veryHighAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryHighBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryHighCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryHighDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highLabel)
                    .addComponent(highAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumLabel)
                    .addComponent(mediumAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mediumDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowLabel)
                    .addComponent(lowAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veryLowMembershipFunctionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryLowLabel)
                    .addComponent(veryLowAParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryLowBParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryLowCParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veryLowDParameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(linguisticTermsPanelLayout.createSequentialGroup()
                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(universeMINLabel)
                            .addComponent(universeMINTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(linguisticTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(universeMAXLabel)
                            .addComponent(universeMAXTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addComponent(linguisticTermsPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lftm_ParametersPanelTabbedPane.addTab("Linguistic terms", linguisticTermsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lftm_ParametersPanelTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lftm_ParametersPanelTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lftm_ParametersPanelTabbedPane.getAccessibleContext().setAccessibleName("BTRM");
    }// </editor-fold>//GEN-END:initComponents

    private void phiSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_phiSliderStateChanged
        phiTextField.setText(String.valueOf(phiSlider.getValue()/(double)phiSlider.getMaximum()));
}//GEN-LAST:event_phiSliderStateChanged

    private void rhoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rhoSliderStateChanged
        rhoTextField.setText(String.valueOf(rhoSlider.getValue()/(double)rhoSlider.getMaximum()));
}//GEN-LAST:event_rhoSliderStateChanged

    private void q0SliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_q0SliderStateChanged
        q0TextField.setText(String.valueOf(q0Slider.getValue()/(double)q0Slider.getMaximum()));
}//GEN-LAST:event_q0SliderStateChanged

    private void numAntsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numAntsSliderStateChanged
        numAntsTextField.setText(String.valueOf(numAntsSlider.getValue()/(double)numAntsSlider.getMaximum()));
}//GEN-LAST:event_numAntsSliderStateChanged

    private void numIterationsSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numIterationsSliderStateChanged
        numIterationsTextField.setText(String.valueOf(numIterationsSlider.getValue()/(double)numIterationsSlider.getMaximum()));
}//GEN-LAST:event_numIterationsSliderStateChanged

    private void alphaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_alphaSliderStateChanged
        alphaTextField.setText(String.valueOf(alphaSlider.getValue()/(double)alphaSlider.getMaximum()));
}//GEN-LAST:event_alphaSliderStateChanged

    private void betaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_betaSliderStateChanged
        betaTextField.setText(String.valueOf(betaSlider.getValue()/(double)betaSlider.getMaximum()));
}//GEN-LAST:event_betaSliderStateChanged

    private void initialPheromoneSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_initialPheromoneSliderStateChanged
        initialPheromoneTextField.setText(String.valueOf(initialPheromoneSlider.getValue()/(double)initialPheromoneSlider.getMaximum()));
}//GEN-LAST:event_initialPheromoneSliderStateChanged

    private void punishmentThresholdSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_punishmentThresholdSliderStateChanged
        punishmentThresholdTextField.setText(String.valueOf(punishmentThresholdSlider.getValue()/(double)punishmentThresholdSlider.getMaximum()));
}//GEN-LAST:event_punishmentThresholdSliderStateChanged

    private void pathLengthFactorSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pathLengthFactorSliderStateChanged
        pathLengthFactorTextField.setText(String.valueOf(pathLengthFactorSlider.getValue()/(double)pathLengthFactorSlider.getMaximum()));
}//GEN-LAST:event_pathLengthFactorSliderStateChanged

    private void transitionThresholdSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_transitionThresholdSliderStateChanged
        transitionThresholdTextField.setText(String.valueOf(transitionThresholdSlider.getValue()/(double)transitionThresholdSlider.getMaximum()));
}//GEN-LAST:event_transitionThresholdSliderStateChanged

    private void veryHighMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_veryHighMembershipFunctionComboBoxItemStateChanged
        boolean trapezoidal = ((String)veryHighMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal");
        veryHighDParameterTextField.setVisible(trapezoidal);
    }//GEN-LAST:event_veryHighMembershipFunctionComboBoxItemStateChanged

    private void highMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_highMembershipFunctionComboBoxItemStateChanged
        boolean trapezoidal = ((String)highMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal");
        highDParameterTextField.setVisible(trapezoidal);
    }//GEN-LAST:event_highMembershipFunctionComboBoxItemStateChanged

    private void mediumMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mediumMembershipFunctionComboBoxItemStateChanged
        boolean trapezoidal = ((String)mediumMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal");
        mediumDParameterTextField.setVisible(trapezoidal);
    }//GEN-LAST:event_mediumMembershipFunctionComboBoxItemStateChanged

    private void lowMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lowMembershipFunctionComboBoxItemStateChanged
        boolean trapezoidal = ((String)lowMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal");
        lowDParameterTextField.setVisible(trapezoidal);
    }//GEN-LAST:event_lowMembershipFunctionComboBoxItemStateChanged

    private void veryLowMembershipFunctionComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_veryLowMembershipFunctionComboBoxItemStateChanged
        boolean trapezoidal = ((String)veryLowMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal");
        veryLowDParameterTextField.setVisible(trapezoidal);
    }//GEN-LAST:event_veryLowMembershipFunctionComboBoxItemStateChanged

    /**
     * Retrieves phi parameter from its corresponding field in the panel
     * @return phi parameter
     */
    protected double get_phi() {
        return Double.parseDouble(phiTextField.getText());
    }

    /**
     * Sets phi parameter into its corresponding field in the panel
     * @param phi phi parameter value to be set
     */
    protected void set_phi(double phi) {
        phiSlider.setValue((int)((phiSlider.getMaximum()-phiSlider.getMinimum())*phi));
    }

    /**
     * Retrieves rho parameter from its corresponding field in the panel
     * @return rho parameter
     */
    protected double get_rho() {
        return Double.parseDouble(rhoTextField.getText());
    }

    /**
     * Sets rho parameter into its corresponding field in the panel
     * @param rho rho parameter value to be set
     */
    protected void set_rho(double rho) {
        rhoSlider.setValue((int)((rhoSlider.getMaximum()-rhoSlider.getMinimum())*rho));
    }

    /**
     * Retrieves q0 parameter from its corresponding field in the panel
     * @return q0 parameter
     */
    protected double get_q0() {
        return Double.parseDouble(q0TextField.getText());
    }

    /**
     * Sets q0 parameter into its corresponding field in the panel
     * @param q0 q0 parameter value to be set
     */
    protected void set_q0(double q0) {
        q0Slider.setValue((int)((q0Slider.getMaximum()-q0Slider.getMinimum())*q0));
    }

    /**
     * Retrieves numAnts parameter from its corresponding field in the panel
     * @return numAnts parameter
     */
    protected double get_numAnts() {
        return Double.parseDouble(numAntsTextField.getText());
    }

    /**
     * Sets numAnts parameter into its corresponding field in the panel
     * @param numAnts numAnts parameter value to be set
     */
    protected void set_numAnts(double numAnts) {
        numAntsSlider.setValue((int)((numAntsSlider.getMaximum()-numAntsSlider.getMinimum())*numAnts));
    }

    /**
     * Retrieves numIterations parameter from its corresponding field in the panel
     * @return numIterations parameter
     */
    protected double get_numIterations() {
        return Double.parseDouble(numIterationsTextField.getText());
    }

    /**
     * Sets numIterations parameter into its corresponding field in the panel
     * @param numIterations numIterations parameter value to be set
     */
    protected void set_numIterations(double numIterations) {
        numIterationsSlider.setValue((int)((numIterationsSlider.getMaximum()-numIterationsSlider.getMinimum())*numIterations));
    }

    /**
     * Retrieves alpha parameter from its corresponding field in the panel
     * @return alpha parameter
     */
    protected double get_alpha() {
        return Double.parseDouble(alphaTextField.getText());
    }

    /**
     * Sets alpha parameter into its corresponding field in the panel
     * @param alpha alpha parameter value to be set
     */
    protected void set_alpha(double alpha) {
        alphaSlider.setValue((int)((alphaSlider.getMaximum()-alphaSlider.getMinimum())*alpha));
    }

    /**
     * Retrieves beta parameter from its corresponding field in the panel
     * @return beta parameter
     */
    protected double get_beta() {
        return Double.parseDouble(betaTextField.getText());
    }

    /**
     * Sets beta parameter into its corresponding field in the panel
     * @param beta beta parameter value to be set
     */
    protected void set_beta(double beta) {
        betaSlider.setValue((int)((betaSlider.getMaximum()-betaSlider.getMinimum())*beta));
    }

    /**
     * Retrieves initialPheromone parameter from its corresponding field in the panel
     * @return initialPheromone parameter
     */
    protected double get_initialPheromone() {
        return Double.parseDouble(initialPheromoneTextField.getText());
    }

    /**
     * Sets initialPheromone parameter into its corresponding field in the panel
     * @param initialPheromone initialPheromone parameter value to be set
     */
    protected void set_initialPheromone(double initialPheromone) {
        initialPheromoneSlider.setValue((int)((initialPheromoneSlider.getMaximum()-initialPheromoneSlider.getMinimum())*initialPheromone));
    }

    /**
     * Retrieves transitionThreshold parameter from its corresponding field in the panel
     * @return transitionThreshold parameter
     */
    protected double get_transitionThreshold() {
        return Double.parseDouble(transitionThresholdTextField.getText());
    }

    /**
     * Sets transitionThreshold parameter into its corresponding field in the panel
     * @param transitionThreshold transitionThreshold parameter value to be set
     */
    protected void set_transitionThreshold(double transitionThreshold) {
        transitionThresholdSlider.setValue((int)((transitionThresholdSlider.getMaximum()-transitionThresholdSlider.getMinimum())*transitionThreshold));
    }

    /**
     * Retrieves pathLengthFactor parameter from its corresponding field in the panel
     * @return pathLengthFactor parameter
     */
    protected double get_pathLengthFactor() {
        return Double.parseDouble(pathLengthFactorTextField.getText());
    }

    /**
     * Sets pathLengthFactor parameter into its corresponding field in the panel
     * @param pathLengthFactor pathLengthFactor parameter value to be set
     */
    protected void set_pathLengthFactor(double pathLengthFactor) {
        pathLengthFactorSlider.setValue((int)((pathLengthFactorSlider.getMaximum()-pathLengthFactorSlider.getMinimum())*pathLengthFactor));
    }

    /**
     * Retrieves punishmentThreshold parameter from its corresponding field in the panel
     * @return punishmentThreshold parameter
     */
    protected double get_punishmentThreshold() {
        return Double.parseDouble(punishmentThresholdTextField.getText());
    }

    /**
     * Sets punishmentThreshold parameter into its corresponding field in the panel
     * @param punishmentThreshold punishmentThreshold parameter value to be set
     */
    protected void set_punishmentThreshold(double punishmentThreshold) {
        punishmentThresholdSlider.setValue((int)((punishmentThresholdSlider.getMaximum()-punishmentThresholdSlider.getMinimum())*punishmentThreshold));
    }

    /**
     * Retrieves U_MIN parameter from its corresponding field in the panel
     * @return U_MIN parameter
     */
    protected double get_U_MIN() {
        return Double.parseDouble(universeMINTextField.getText());
    }

    /**
     * Sets U_MIN parameter into its corresponding field in the panel
     * @param U_MIN U_MIN parameter value to be set
     */
    protected void set_U_MIN(double U_MIN) {
        universeMINTextField.setText(String.valueOf(U_MIN));
    }

    /**
     * Retrieves U_MAX parameter from its corresponding field in the panel
     * @return U_MAX parameter
     */
    protected double get_U_MAX() {
        return Double.parseDouble(universeMAXTextField.getText());
    }

    /**
     * Sets U_MAX parameter into its corresponding field in the panel
     * @param U_MAX U_MAX parameter value to be set
     */
    protected void set_U_MAX(double U_MAX) {
        universeMAXTextField.setText(String.valueOf(U_MAX));
    }

    /**
     * Retrieves linguisticTerms parameter from its corresponding fields in the panel
     * @return linguisticTerms parameter
     */
    protected Collection<LinguisticTerm> getLinguisticTerms() {
        Vector<LinguisticTerm> linguisticTerms = new Vector<LinguisticTerm>();
        LinguisticTerm veryHigh = null;
        LinguisticTerm high = null;
        LinguisticTerm medium = null;
        LinguisticTerm low = null;
        LinguisticTerm veryLow = null;
        double U_MAX = get_U_MAX();
        double U_MIN = get_U_MIN();

        double veryHighAParameter = Double.parseDouble(veryHighAParameterTextField.getText());
        double veryHighBParameter = Double.parseDouble(veryHighBParameterTextField.getText());
        double veryHighCParameter = Double.parseDouble(veryHighCParameterTextField.getText());
        if (((String)veryHighMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal"))  {
            double veryHighDParameter = Double.parseDouble(veryHighDParameterTextField.getText());
            veryHigh = new LinguisticTerm("Very High",
                    new MembershipFunctionTrapezoidal(veryHighAParameter*U_MAX,veryHighBParameter*U_MAX,veryHighCParameter*U_MAX,veryHighDParameter*U_MAX));
        } else
            veryHigh = new LinguisticTerm("Very High",
                    new MembershipFunctionTriangular(veryHighAParameter*U_MAX,veryHighBParameter*U_MAX,veryHighCParameter*U_MAX));

        double highAParameter = Double.parseDouble(highAParameterTextField.getText());
        double highBParameter = Double.parseDouble(highBParameterTextField.getText());
        double highCParameter = Double.parseDouble(highCParameterTextField.getText());
        if (((String)highMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal"))  {
            double highDParameter = Double.parseDouble(highDParameterTextField.getText());
            high = new LinguisticTerm("High",
                    new MembershipFunctionTrapezoidal(highAParameter*U_MAX,highBParameter*U_MAX,highCParameter*U_MAX,highDParameter*U_MAX));
        } else
            high = new LinguisticTerm("High",
                    new MembershipFunctionTriangular(highAParameter*U_MAX,highBParameter*U_MAX,highCParameter*U_MAX));

        double mediumAParameter = Double.parseDouble(mediumAParameterTextField.getText());
        double mediumBParameter = Double.parseDouble(mediumBParameterTextField.getText());
        double mediumCParameter = Double.parseDouble(mediumCParameterTextField.getText());
        if (((String)mediumMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal"))  {
            double mediumDParameter = Double.parseDouble(mediumDParameterTextField.getText());
            medium = new LinguisticTerm("Medium",
                    new MembershipFunctionTrapezoidal(mediumAParameter*U_MAX,mediumBParameter*U_MAX,mediumCParameter*U_MAX,mediumDParameter*U_MAX));
        } else
            medium = new LinguisticTerm("Medium",
                    new MembershipFunctionTriangular(mediumAParameter*U_MAX,mediumBParameter*U_MAX,mediumCParameter*U_MAX));

        double lowAParameter = Double.parseDouble(lowAParameterTextField.getText());
        double lowBParameter = Double.parseDouble(lowBParameterTextField.getText());
        double lowCParameter = Double.parseDouble(lowCParameterTextField.getText());
        if (((String)lowMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal"))  {
            double lowDParameter = Double.parseDouble(lowDParameterTextField.getText());
            low = new LinguisticTerm("Low",
                    new MembershipFunctionTrapezoidal(lowAParameter*U_MAX,lowBParameter*U_MAX,lowCParameter*U_MAX,lowDParameter*U_MAX));
        } else
            low = new LinguisticTerm("Low",
                    new MembershipFunctionTriangular(lowAParameter*U_MAX,lowBParameter*U_MAX,lowCParameter*U_MAX));

        double veryLowAParameter = Double.parseDouble(veryLowAParameterTextField.getText());
        double veryLowBParameter = Double.parseDouble(veryLowBParameterTextField.getText());
        double veryLowCParameter = Double.parseDouble(veryLowCParameterTextField.getText());
        if (((String)veryLowMembershipFunctionComboBox.getSelectedItem()).equals("Trapezoidal"))  {
            double veryLowDParameter = Double.parseDouble(veryLowDParameterTextField.getText());
            veryLow = new LinguisticTerm("Very Low",
                    new MembershipFunctionTrapezoidal(veryLowAParameter*U_MAX,veryLowBParameter*U_MAX,veryLowCParameter*U_MAX,veryLowDParameter*U_MAX));
        } else
            veryLow = new LinguisticTerm("Very Low",
                    new MembershipFunctionTriangular(veryLowAParameter*U_MAX,veryLowBParameter*U_MAX,veryLowCParameter*U_MAX));

        veryHigh.setDefuzzifier(new DefuzzifierCenterOfGravity(U_MIN,U_MAX));
        high.setDefuzzifier(new DefuzzifierCenterOfGravity(U_MIN,U_MAX));
        medium.setDefuzzifier(new DefuzzifierCenterOfGravity(U_MIN,U_MAX));
        low.setDefuzzifier(new DefuzzifierCenterOfGravity(U_MIN,U_MAX));
        veryLow.setDefuzzifier(new DefuzzifierCenterOfGravity(U_MIN,U_MAX));

        linguisticTerms.add(veryHigh);
        linguisticTerms.add(high);
        linguisticTerms.add(medium);
        linguisticTerms.add(low);
        linguisticTerms.add(veryLow);

        return linguisticTerms;
    }

    /**
     * Sets linguisticTerms parameter into its corresponding fields in the panel
     * @param linguisticTerms linguisticTerms parameter value to be set
     */
    protected void set_LinguisticTerms(Collection<LinguisticTerm> linguisticTerms) {
        for (LinguisticTerm linguisticTerm : linguisticTerms) {
            String termName = linguisticTerm.getTermName();
            if (termName.equals("Very High")) {
                if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTriangular) {
                    veryHighMembershipFunctionComboBox.setSelectedItem("Triangular");
                    veryHighAParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_min()));
                    veryHighBParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_med()));
                    veryHighCParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_max()));
                } else if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTrapezoidal) {
                    veryHighMembershipFunctionComboBox.setSelectedItem("Trapezoidal");
                    veryHighAParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_min()));
                    veryHighBParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medLow()));
                    veryHighCParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medHigh()));
                    veryHighDParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_max()));
                }
            } else if (termName.equals("High")) {
                if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTriangular) {
                    highMembershipFunctionComboBox.setSelectedItem("Triangular");
                    highAParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_min()));
                    highBParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_med()));
                    highCParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_max()));
                } else if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTrapezoidal) {
                    highMembershipFunctionComboBox.setSelectedItem("Trapezoidal");
                    highAParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_min()));
                    highBParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medLow()));
                    highCParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medHigh()));
                    highDParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_max()));
                }
            } else if (termName.equals("Medium")) {
                if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTriangular) {
                    mediumMembershipFunctionComboBox.setSelectedItem("Triangular");
                    mediumAParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_min()));
                    mediumBParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_med()));
                    mediumCParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_max()));
                } else if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTrapezoidal) {
                    mediumMembershipFunctionComboBox.setSelectedItem("Trapezoidal");
                    mediumAParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_min()));
                    mediumBParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medLow()));
                    mediumCParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medHigh()));
                    mediumDParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_max()));
                }
            } else if (termName.equals("Low")) {
                if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTriangular) {
                    lowMembershipFunctionComboBox.setSelectedItem("Triangular");
                    lowAParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_min()));
                    lowBParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_med()));
                    lowCParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_max()));
                } else if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTrapezoidal) {
                    lowMembershipFunctionComboBox.setSelectedItem("Trapezoidal");
                    lowAParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_min()));
                    lowBParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medLow()));
                    lowCParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medHigh()));
                    lowDParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_max()));
                }
            } else if (termName.equals("Very Low")) {
                if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTriangular) {
                    veryLowMembershipFunctionComboBox.setSelectedItem("Triangular");
                    veryLowAParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_min()));
                    veryLowBParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_med()));
                    veryLowCParameterTextField.setText(String.valueOf(((MembershipFunctionTriangular)linguisticTerm.get_membershipFunction()).get_max()));
                } else if (linguisticTerm.get_membershipFunction() instanceof MembershipFunctionTrapezoidal) {
                    veryLowMembershipFunctionComboBox.setSelectedItem("Trapezoidal");
                    veryLowAParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_min()));
                    veryLowBParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medLow()));
                    veryLowCParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_medHigh()));
                    veryLowDParameterTextField.setText(String.valueOf(((MembershipFunctionTrapezoidal)linguisticTerm.get_membershipFunction()).get_max()));
                }
            }
        }

        fuzzySetPanel = new FuzzySetPanel(linguisticTerms);
        fuzzySetPanel.setPreferredSize(linguisticTermsPanelContainer.getPreferredSize());

        ((javax.swing.GroupLayout)linguisticTermsPanel.getLayout()).replace(linguisticTermsPanelContainer,fuzzySetPanel);
        fuzzySetPanelAux = fuzzySetPanel;
        linguisticTermsPanelContainer = fuzzySetPanelAux;
    }

    @Override
    public TRMParameters get_TRMParameters() {
        LFTM_Parameters lftmParameters = new LFTM_Parameters();

        lftmParameters.set_phi(get_phi());
        lftmParameters.set_rho(get_rho());
        lftmParameters.set_q0(get_q0());
        lftmParameters.set_numAnts(get_numAnts());
        lftmParameters.set_numIterations(get_numIterations());
        lftmParameters.set_alpha(get_alpha());
        lftmParameters.set_beta(get_beta());
        lftmParameters.set_initialPheromone(get_initialPheromone());
        lftmParameters.set_transitionThreshold(get_transitionThreshold());
        lftmParameters.set_pathLengthFactor(get_pathLengthFactor());
        lftmParameters.set_punishmentThreshold(get_punishmentThreshold());
        lftmParameters.set_U_MIN(get_U_MIN());
        lftmParameters.set_U_MAX(get_U_MAX());
        lftmParameters.set_linguisticTerms(getLinguisticTerms());

        return lftmParameters;
    }

    @Override
    public void set_TRMParameters(TRMParameters trmParameters) {
        LFTM_Parameters lftmParameters = (LFTM_Parameters)trmParameters;

        set_phi(lftmParameters.get_phi());
        set_rho(lftmParameters.get_rho());
        set_q0(lftmParameters.get_q0());
        set_numAnts(lftmParameters.get_numAnts());
        set_numIterations(lftmParameters.get_numIterations());
        set_alpha(lftmParameters.get_alpha());
        set_beta(lftmParameters.get_beta());
        set_initialPheromone(lftmParameters.get_initialPheromone());
        set_transitionThreshold(lftmParameters.get_transitionThreshold());
        set_pathLengthFactor(lftmParameters.get_pathLengthFactor());
        set_punishmentThreshold(lftmParameters.get_punishmentThreshold());
        set_U_MIN(LFTM_Parameters.get_U_MIN());
        set_U_MAX(LFTM_Parameters.get_U_MAX());
        set_LinguisticTerms(LFTM_Parameters.get_linguisticTerms());
    }

    @Override
    public void setEnabled(boolean enabled) {
        phiLabel.setEnabled(enabled);
        phiSlider.setEnabled(enabled);
        rhoLabel.setEnabled(enabled);
        rhoSlider.setEnabled(enabled);
        q0Label.setEnabled(enabled);
        q0Slider.setEnabled(enabled);
        numAntsLabel.setEnabled(enabled);
        numAntsSlider.setEnabled(enabled);
        numIterationsLabel.setEnabled(enabled);
        numIterationsSlider.setEnabled(enabled);
        alphaLabel.setEnabled(enabled);
        alphaSlider.setEnabled(enabled);
        betaLabel.setEnabled(enabled);
        betaSlider.setEnabled(enabled);
        initialPheromoneLabel.setEnabled(enabled);
        initialPheromoneSlider.setEnabled(enabled);
        transitionThresholdLabel.setEnabled(enabled);
        transitionThresholdSlider.setEnabled(enabled);
        pathLengthFactorLabel.setEnabled(enabled);
        pathLengthFactorSlider.setEnabled(enabled);
        punishmentThresholdLabel.setEnabled(enabled);
        punishmentThresholdSlider.setEnabled(enabled);
        membershipFunctionLabel.setEnabled(enabled);
        aParameterLabel.setEnabled(enabled);
        bParameterLabel.setEnabled(enabled);
        cParameterLabel.setEnabled(enabled);
        dParameterLabel.setEnabled(enabled);
        veryHighLabel.setEnabled(enabled);
        veryHighMembershipFunctionComboBox.setEnabled(enabled);
        veryHighAParameterTextField.setEnabled(enabled);
        veryHighBParameterTextField.setEnabled(enabled);
        veryHighCParameterTextField.setEnabled(enabled);
        veryHighDParameterTextField.setEnabled(enabled);
        highLabel.setEnabled(enabled);
        highMembershipFunctionComboBox.setEnabled(enabled);
        highAParameterTextField.setEnabled(enabled);
        highBParameterTextField.setEnabled(enabled);
        highCParameterTextField.setEnabled(enabled);
        highDParameterTextField.setEnabled(enabled);
        mediumLabel.setEnabled(enabled);
        mediumMembershipFunctionComboBox.setEnabled(enabled);
        mediumAParameterTextField.setEnabled(enabled);
        mediumBParameterTextField.setEnabled(enabled);
        mediumCParameterTextField.setEnabled(enabled);
        mediumDParameterTextField.setEnabled(enabled);
        lowLabel.setEnabled(enabled);
        lowMembershipFunctionComboBox.setEnabled(enabled);
        lowAParameterTextField.setEnabled(enabled);
        lowBParameterTextField.setEnabled(enabled);
        lowCParameterTextField.setEnabled(enabled);
        lowDParameterTextField.setEnabled(enabled);
        veryLowLabel.setEnabled(enabled);
        veryLowMembershipFunctionComboBox.setEnabled(enabled);
        veryLowAParameterTextField.setEnabled(enabled);
        veryLowBParameterTextField.setEnabled(enabled);
        veryLowCParameterTextField.setEnabled(enabled);
        veryLowDParameterTextField.setEnabled(enabled);
        universeMINLabel.setEnabled(enabled);
        universeMINTextField.setEnabled(enabled);
        universeMAXLabel.setEnabled(enabled);
        universeMAXTextField.setEnabled(enabled);
        linguisticTermsPanelContainer.setEnabled(enabled);
        fuzzySetPanelAux.setEnabled(enabled);
        fuzzySetPanel.setEnabled(enabled);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aParameterLabel;
    private javax.swing.JLabel alphaLabel;
    private javax.swing.JSlider alphaSlider;
    private javax.swing.JTextField alphaTextField;
    private javax.swing.JLabel bParameterLabel;
    private javax.swing.JLabel betaLabel;
    private javax.swing.JSlider betaSlider;
    private javax.swing.JTextField betaTextField;
    private javax.swing.JPanel btrm_ParametersPanel;
    private javax.swing.JLabel cParameterLabel;
    private javax.swing.JLabel dParameterLabel;
    private javax.swing.JTextField highAParameterTextField;
    private javax.swing.JTextField highBParameterTextField;
    private javax.swing.JTextField highCParameterTextField;
    private javax.swing.JTextField highDParameterTextField;
    private javax.swing.JLabel highLabel;
    private javax.swing.JComboBox highMembershipFunctionComboBox;
    private javax.swing.JLabel initialPheromoneLabel;
    private javax.swing.JSlider initialPheromoneSlider;
    private javax.swing.JTextField initialPheromoneTextField;
    private javax.swing.JTabbedPane lftm_ParametersPanelTabbedPane;
    private javax.swing.JPanel linguisticTermsPanel;
    private javax.swing.JPanel linguisticTermsPanelContainer;
    private javax.swing.JTextField lowAParameterTextField;
    private javax.swing.JTextField lowBParameterTextField;
    private javax.swing.JTextField lowCParameterTextField;
    private javax.swing.JTextField lowDParameterTextField;
    private javax.swing.JLabel lowLabel;
    private javax.swing.JComboBox lowMembershipFunctionComboBox;
    private javax.swing.JTextField mediumAParameterTextField;
    private javax.swing.JTextField mediumBParameterTextField;
    private javax.swing.JTextField mediumCParameterTextField;
    private javax.swing.JTextField mediumDParameterTextField;
    private javax.swing.JLabel mediumLabel;
    private javax.swing.JComboBox mediumMembershipFunctionComboBox;
    private javax.swing.JLabel membershipFunctionLabel;
    private javax.swing.JLabel numAntsLabel;
    private javax.swing.JSlider numAntsSlider;
    private javax.swing.JTextField numAntsTextField;
    private javax.swing.JLabel numIterationsLabel;
    private javax.swing.JSlider numIterationsSlider;
    private javax.swing.JTextField numIterationsTextField;
    private javax.swing.JLabel pathLengthFactorLabel;
    private javax.swing.JSlider pathLengthFactorSlider;
    private javax.swing.JTextField pathLengthFactorTextField;
    private javax.swing.JLabel phiLabel;
    private javax.swing.JSlider phiSlider;
    private javax.swing.JTextField phiTextField;
    private javax.swing.JLabel punishmentThresholdLabel;
    private javax.swing.JSlider punishmentThresholdSlider;
    private javax.swing.JTextField punishmentThresholdTextField;
    private javax.swing.JLabel q0Label;
    private javax.swing.JSlider q0Slider;
    private javax.swing.JTextField q0TextField;
    private javax.swing.JLabel rhoLabel;
    private javax.swing.JSlider rhoSlider;
    private javax.swing.JTextField rhoTextField;
    private javax.swing.JLabel transitionThresholdLabel;
    private javax.swing.JSlider transitionThresholdSlider;
    private javax.swing.JTextField transitionThresholdTextField;
    private javax.swing.JLabel universeMAXLabel;
    private javax.swing.JTextField universeMAXTextField;
    private javax.swing.JLabel universeMINLabel;
    private javax.swing.JTextField universeMINTextField;
    private javax.swing.JTextField veryHighAParameterTextField;
    private javax.swing.JTextField veryHighBParameterTextField;
    private javax.swing.JTextField veryHighCParameterTextField;
    private javax.swing.JTextField veryHighDParameterTextField;
    private javax.swing.JLabel veryHighLabel;
    private javax.swing.JComboBox veryHighMembershipFunctionComboBox;
    private javax.swing.JTextField veryLowAParameterTextField;
    private javax.swing.JTextField veryLowBParameterTextField;
    private javax.swing.JTextField veryLowCParameterTextField;
    private javax.swing.JTextField veryLowDParameterTextField;
    private javax.swing.JLabel veryLowLabel;
    private javax.swing.JComboBox veryLowMembershipFunctionComboBox;
    // End of variables declaration//GEN-END:variables

}
