/**
 *  "TRMSim-WSN, Trust and Reputation Models Simulator for Wireless
 * Sensor Networks" is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version always keeping
 * the additional terms specified in this license.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 *
 * Additional Terms of this License
 * --------------------------------
 *
 * 1. It is Required the preservation of specified reasonable legal notices
 *   and author attributions in that material and in the Appropriate Legal
 *   Notices displayed by works containing it.
 *
 * 2. It is limited the use for publicity purposes of names of licensors or
 *   authors of the material.
 *
 * 3. It is Required indemnification of licensors and authors of that material
 *   by anyone who conveys the material (or modified versions of it) with
 *   contractual assumptions of liability to the recipient, for any liability
 *   that these contractual assumptions directly impose on those licensors
 *   and authors.
 *
 * 4. It is Prohibited misrepresentation of the origin of that material, and it is
 *   required that modified versions of such material be marked in reasonable
 *   ways as different from the original version.
 *
 * 5. It is Declined to grant rights under trademark law for use of some trade
 *   names, trademarks, or service marks.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (lgpl.txt).  If not, see <http://www.gnu.org/licenses/>
*/

package es.ants.felixgm.trmsim_wsn.gui.parameterpanels;

import es.ants.felixgm.trmsim_wsn.trm.TRMParameters;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.FuzzySetPanel;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.LinguisticTerm;
import es.ants.felixgm.trmsim_wsn.trm.libs.fuzzylib.MembershipFunctionGaussian;
import es.ants.felixgm.trmsim_wsn.trm.trip.TRIP_Parameters;
import java.util.Collection;
import java.util.LinkedList;

/**
 * <p>This class represents the panel used to retrieve the parameters of TRIP</p>
 * @author <a href="http://ants.dif.um.es/~felixgm/en" target="_blank">F&eacute;lix G&oacute;mez M&aacute;rmol</a>, <a href="http://webs.um.es/gregorio" target="_blank">Gregorio Mart&iacute;nez P&eacute;rez</a>
 * @version 0.5
 * @since 0.5
 */
public class TRIP_ParametersPanel extends TRMParametersPanel {
    protected FuzzySetPanel fuzzySetPanelAux, fuzzySetPanel;
    private LinguisticTerm notTrustFuzzySet,moreOrLessTrustFuzzySet,trustFuzzySet;
    private Collection<LinguisticTerm> trustLevels;

    /** Creates new form TRIP_ParametersPanel */
    public TRIP_ParametersPanel() {
        fuzzySetPanelAux = new FuzzySetPanel();
        fuzzySetPanel = new FuzzySetPanel();
        initComponents();
        notTrustFuzzySet = new LinguisticTerm("Not Trust",
                    new MembershipFunctionGaussian(get_notTrustFuzzySetMean(),get_notTrustFuzzySetStDev()));
        moreOrLessTrustFuzzySet = new LinguisticTerm("+/- Trust",
                    new MembershipFunctionGaussian(get_moreOrLessTrustFuzzySetMean(),get_moreOrLessTrustFuzzySetStDev()));
        trustFuzzySet = new LinguisticTerm("Trust",
                    new MembershipFunctionGaussian(get_trustFuzzySetMean(),get_trustFuzzySetStDev()));
        trustLevels = new LinkedList<LinguisticTerm>();
        trustLevels.add(notTrustFuzzySet);
        trustLevels.add(moreOrLessTrustFuzzySet);
        trustLevels.add(trustFuzzySet);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initialAlphaLabel = new javax.swing.JLabel();
        initialAlphaSlider = new javax.swing.JSlider();
        initialAlphaTextField = new javax.swing.JTextField();
        initialBetaSlider = new javax.swing.JSlider();
        initialBetaTextField = new javax.swing.JTextField();
        initialBetaLabel = new javax.swing.JLabel();
        initialGammaSlider = new javax.swing.JSlider();
        initialGammaTextField = new javax.swing.JTextField();
        initialGammaLabel = new javax.swing.JLabel();
        trustLevelsPanelContainer = new javax.swing.JPanel();
        notTrustFuzzySetMeanLabel = new javax.swing.JLabel();
        notTrustFuzzySetMeanSlider = new javax.swing.JSlider();
        notTrustFuzzySetStDevSlider = new javax.swing.JSlider();
        notTrustFuzzySetStDevLabel = new javax.swing.JLabel();
        moreOrLessTrustFuzzySetStDevSlider = new javax.swing.JSlider();
        moreOrLessTrustFuzzySetStDevLabel = new javax.swing.JLabel();
        moreOrLessTrustFuzzySetMeanSlider = new javax.swing.JSlider();
        moreOrLessTrustFuzzySetMeanLabel = new javax.swing.JLabel();
        trustFuzzySetStDevSlider = new javax.swing.JSlider();
        trustFuzzySetStDevLabel = new javax.swing.JLabel();
        trustFuzzySetMeanSlider = new javax.swing.JSlider();
        trustFuzzySetMeanLabel = new javax.swing.JLabel();
        notTrustFuzzySetMeanTextField = new javax.swing.JTextField();
        notTrustFuzzySetStDevTextField = new javax.swing.JTextField();
        moreOrLessTrustFuzzySetMeanTextField = new javax.swing.JTextField();
        moreOrLessTrustFuzzySetStDevTextField = new javax.swing.JTextField();
        trustFuzzySetMeanTextField = new javax.swing.JTextField();
        trustFuzzySetStDevTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        rsuPercentageTextField = new javax.swing.JTextField();
        rsuPercentageSlider = new javax.swing.JSlider();
        rsuPercentageLabel = new javax.swing.JLabel();
        numHopsQueriedRecommendersLabel = new javax.swing.JLabel();
        numHopsQueriedRecommendersSpinner = new javax.swing.JSpinner();

        initialAlphaLabel.setText("Initial alpha");
        initialAlphaLabel.setEnabled(false);

        initialAlphaSlider.setValue(0);
        initialAlphaSlider.setEnabled(false);
        initialAlphaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                initialAlphaSliderStateChanged(evt);
            }
        });

        initialAlphaTextField.setEditable(false);
        initialAlphaTextField.setText("0.0");

        initialBetaSlider.setValue(0);
        initialBetaSlider.setEnabled(false);
        initialBetaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                initialBetaSliderStateChanged(evt);
            }
        });

        initialBetaTextField.setEditable(false);
        initialBetaTextField.setText("0.0");

        initialBetaLabel.setText("Initial beta");
        initialBetaLabel.setEnabled(false);

        initialGammaSlider.setValue(0);
        initialGammaSlider.setEnabled(false);
        initialGammaSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                initialGammaSliderStateChanged(evt);
            }
        });

        initialGammaTextField.setEditable(false);
        initialGammaTextField.setText("0.0");

        initialGammaLabel.setText("Initial gamma");
        initialGammaLabel.setEnabled(false);

        trustLevelsPanelContainer.add(fuzzySetPanelAux,null);
        trustLevelsPanelContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout trustLevelsPanelContainerLayout = new javax.swing.GroupLayout(trustLevelsPanelContainer);
        trustLevelsPanelContainer.setLayout(trustLevelsPanelContainerLayout);
        trustLevelsPanelContainerLayout.setHorizontalGroup(
            trustLevelsPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        trustLevelsPanelContainerLayout.setVerticalGroup(
            trustLevelsPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        notTrustFuzzySetMeanLabel.setText("\"Not Trust\" Fuzzy Set Mean");
        notTrustFuzzySetMeanLabel.setEnabled(false);

        notTrustFuzzySetMeanSlider.setValue(30);
        notTrustFuzzySetMeanSlider.setEnabled(false);
        notTrustFuzzySetMeanSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                notTrustFuzzySetMeanSliderStateChanged(evt);
            }
        });

        notTrustFuzzySetStDevSlider.setValue(0);
        notTrustFuzzySetStDevSlider.setEnabled(false);
        notTrustFuzzySetStDevSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                notTrustFuzzySetStDevSliderStateChanged(evt);
            }
        });

        notTrustFuzzySetStDevLabel.setText("\"Not Trust\" Fuzzy Set Standard Deviation");
        notTrustFuzzySetStDevLabel.setEnabled(false);

        moreOrLessTrustFuzzySetStDevSlider.setValue(0);
        moreOrLessTrustFuzzySetStDevSlider.setEnabled(false);
        moreOrLessTrustFuzzySetStDevSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                moreOrLessTrustFuzzySetStDevSliderStateChanged(evt);
            }
        });

        moreOrLessTrustFuzzySetStDevLabel.setText("\"+/- Trust\" Fuzzy Set Standard Deviation");
        moreOrLessTrustFuzzySetStDevLabel.setEnabled(false);

        moreOrLessTrustFuzzySetMeanSlider.setValue(0);
        moreOrLessTrustFuzzySetMeanSlider.setEnabled(false);
        moreOrLessTrustFuzzySetMeanSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                moreOrLessTrustFuzzySetMeanSliderStateChanged(evt);
            }
        });

        moreOrLessTrustFuzzySetMeanLabel.setText("\"+/- Trust\" Fuzzy Set Mean");
        moreOrLessTrustFuzzySetMeanLabel.setEnabled(false);

        trustFuzzySetStDevSlider.setValue(0);
        trustFuzzySetStDevSlider.setEnabled(false);
        trustFuzzySetStDevSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                trustFuzzySetStDevSliderStateChanged(evt);
            }
        });

        trustFuzzySetStDevLabel.setText("\"Not Trust\" Fuzzy Set Standard Deviation");
        trustFuzzySetStDevLabel.setEnabled(false);

        trustFuzzySetMeanSlider.setValue(0);
        trustFuzzySetMeanSlider.setEnabled(false);
        trustFuzzySetMeanSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                trustFuzzySetMeanSliderStateChanged(evt);
            }
        });

        trustFuzzySetMeanLabel.setText("\"Trust\" Fuzzy Set Mean");
        trustFuzzySetMeanLabel.setEnabled(false);

        notTrustFuzzySetMeanTextField.setEditable(false);
        notTrustFuzzySetMeanTextField.setText("0.0");

        notTrustFuzzySetStDevTextField.setEditable(false);
        notTrustFuzzySetStDevTextField.setText("0.0");

        moreOrLessTrustFuzzySetMeanTextField.setEditable(false);
        moreOrLessTrustFuzzySetMeanTextField.setText("0.0");

        moreOrLessTrustFuzzySetStDevTextField.setEditable(false);
        moreOrLessTrustFuzzySetStDevTextField.setText("0.0");

        trustFuzzySetMeanTextField.setEditable(false);
        trustFuzzySetMeanTextField.setText("0.0");

        trustFuzzySetStDevTextField.setEditable(false);
        trustFuzzySetStDevTextField.setText("0.0");

        rsuPercentageTextField.setEditable(false);
        rsuPercentageTextField.setText("0.0");

        rsuPercentageSlider.setValue(0);
        rsuPercentageSlider.setEnabled(false);
        rsuPercentageSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rsuPercentageSliderStateChanged(evt);
            }
        });

        rsuPercentageLabel.setText("Percentage of RSUs");
        rsuPercentageLabel.setEnabled(false);

        numHopsQueriedRecommendersLabel.setText("Num hops to queried recommenders");
        numHopsQueriedRecommendersLabel.setEnabled(false);

        numHopsQueriedRecommendersSpinner.setModel(new javax.swing.SpinnerNumberModel());
        numHopsQueriedRecommendersSpinner.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(initialBetaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(initialGammaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trustFuzzySetStDevLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(trustFuzzySetStDevSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trustFuzzySetStDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(initialBetaSlider, 0, 165, Short.MAX_VALUE)
                                .addComponent(initialGammaSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(initialAlphaSlider, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE))
                            .addComponent(initialAlphaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(initialAlphaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rsuPercentageLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rsuPercentageSlider, 0, 165, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rsuPercentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(numHopsQueriedRecommendersLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(initialGammaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(initialBetaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numHopsQueriedRecommendersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1)
                    .addComponent(notTrustFuzzySetMeanLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moreOrLessTrustFuzzySetStDevLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notTrustFuzzySetStDevLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(moreOrLessTrustFuzzySetMeanSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(moreOrLessTrustFuzzySetMeanLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notTrustFuzzySetStDevSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moreOrLessTrustFuzzySetMeanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notTrustFuzzySetStDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moreOrLessTrustFuzzySetStDevSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trustFuzzySetMeanSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trustFuzzySetMeanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moreOrLessTrustFuzzySetStDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(notTrustFuzzySetMeanTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(trustLevelsPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(trustFuzzySetMeanLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notTrustFuzzySetMeanSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(initialAlphaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initialAlphaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rsuPercentageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rsuPercentageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rsuPercentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(initialAlphaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(initialBetaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(initialBetaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(initialGammaLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(initialBetaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numHopsQueriedRecommendersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(initialGammaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(initialGammaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(numHopsQueriedRecommendersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notTrustFuzzySetMeanLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notTrustFuzzySetMeanSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notTrustFuzzySetMeanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notTrustFuzzySetStDevLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(notTrustFuzzySetStDevSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moreOrLessTrustFuzzySetMeanLabel))
                            .addComponent(notTrustFuzzySetStDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moreOrLessTrustFuzzySetMeanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moreOrLessTrustFuzzySetMeanSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moreOrLessTrustFuzzySetStDevLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moreOrLessTrustFuzzySetStDevSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trustFuzzySetMeanLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trustFuzzySetMeanSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moreOrLessTrustFuzzySetStDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(trustFuzzySetMeanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trustFuzzySetStDevLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(trustFuzzySetStDevSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trustFuzzySetStDevTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(trustLevelsPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initialAlphaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_initialAlphaSliderStateChanged
        initialAlphaTextField.setText(String.valueOf(initialAlphaSlider.getValue()/(double)initialAlphaSlider.getMaximum()));
    }//GEN-LAST:event_initialAlphaSliderStateChanged

    private void initialBetaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_initialBetaSliderStateChanged
        initialBetaTextField.setText(String.valueOf(initialBetaSlider.getValue()/(double)initialBetaSlider.getMaximum()));
    }//GEN-LAST:event_initialBetaSliderStateChanged

    private void initialGammaSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_initialGammaSliderStateChanged
        initialGammaTextField.setText(String.valueOf(initialGammaSlider.getValue()/(double)initialGammaSlider.getMaximum()));
    }//GEN-LAST:event_initialGammaSliderStateChanged

    private void notTrustFuzzySetMeanSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_notTrustFuzzySetMeanSliderStateChanged
        ((MembershipFunctionGaussian)notTrustFuzzySet.get_membershipFunction()).set_mean(get_notTrustFuzzySetMean());
        notTrustFuzzySetMeanTextField.setText(String.valueOf(get_notTrustFuzzySetMean()));
        updateTrustLevelsPanelContainer(trustLevels);
    }//GEN-LAST:event_notTrustFuzzySetMeanSliderStateChanged

    private void notTrustFuzzySetStDevSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_notTrustFuzzySetStDevSliderStateChanged
        ((MembershipFunctionGaussian)notTrustFuzzySet.get_membershipFunction()).set_stDev(get_notTrustFuzzySetStDev());
        notTrustFuzzySetStDevTextField.setText(String.valueOf(get_notTrustFuzzySetStDev()));
        updateTrustLevelsPanelContainer(trustLevels);
    }//GEN-LAST:event_notTrustFuzzySetStDevSliderStateChanged

    private void moreOrLessTrustFuzzySetMeanSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_moreOrLessTrustFuzzySetMeanSliderStateChanged
        ((MembershipFunctionGaussian)moreOrLessTrustFuzzySet.get_membershipFunction()).set_mean(get_moreOrLessTrustFuzzySetMean());
        moreOrLessTrustFuzzySetMeanTextField.setText(String.valueOf(get_moreOrLessTrustFuzzySetMean()));
        updateTrustLevelsPanelContainer(trustLevels);
    }//GEN-LAST:event_moreOrLessTrustFuzzySetMeanSliderStateChanged

    private void moreOrLessTrustFuzzySetStDevSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_moreOrLessTrustFuzzySetStDevSliderStateChanged
        ((MembershipFunctionGaussian)moreOrLessTrustFuzzySet.get_membershipFunction()).set_stDev(get_moreOrLessTrustFuzzySetStDev());
        moreOrLessTrustFuzzySetStDevTextField.setText(String.valueOf(get_moreOrLessTrustFuzzySetStDev()));
        updateTrustLevelsPanelContainer(trustLevels);
    }//GEN-LAST:event_moreOrLessTrustFuzzySetStDevSliderStateChanged

    private void trustFuzzySetMeanSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_trustFuzzySetMeanSliderStateChanged
        ((MembershipFunctionGaussian)trustFuzzySet.get_membershipFunction()).set_mean(get_trustFuzzySetMean());
        trustFuzzySetMeanTextField.setText(String.valueOf(get_trustFuzzySetMean()));
        updateTrustLevelsPanelContainer(trustLevels);
    }//GEN-LAST:event_trustFuzzySetMeanSliderStateChanged

    private void trustFuzzySetStDevSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_trustFuzzySetStDevSliderStateChanged
        ((MembershipFunctionGaussian)trustFuzzySet.get_membershipFunction()).set_stDev(get_trustFuzzySetStDev());
        trustFuzzySetStDevTextField.setText(String.valueOf(get_trustFuzzySetStDev()));
        updateTrustLevelsPanelContainer(trustLevels);
    }//GEN-LAST:event_trustFuzzySetStDevSliderStateChanged

    private void rsuPercentageSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rsuPercentageSliderStateChanged
        rsuPercentageTextField.setText(String.valueOf(rsuPercentageSlider.getValue()/(double)rsuPercentageSlider.getMaximum()));
    }//GEN-LAST:event_rsuPercentageSliderStateChanged

    private void updateTrustLevelsPanelContainer(Collection<LinguisticTerm> linguisticTerms){
        fuzzySetPanel = new FuzzySetPanel(linguisticTerms);
        fuzzySetPanel.setPreferredSize(trustLevelsPanelContainer.getPreferredSize());

        ((javax.swing.GroupLayout)this.getLayout()).replace(trustLevelsPanelContainer,fuzzySetPanel);
        fuzzySetPanelAux = fuzzySetPanel;
        trustLevelsPanelContainer = fuzzySetPanelAux;
    }

    /**
     * Retrieves initialAlpha parameter from its corresponding field in the panel
     * @return initialAlpha parameter
     */
    protected double get_initialAlpha() {
        return Double.parseDouble(initialAlphaTextField.getText());
    }

    /**
     * Sets initialAlpha parameter into its corresponding field in the panel
     * @param initialAlpha initialAlpha parameter value to be set
     */
    protected void set_initialAlpha(double initialAlpha) {
        initialAlphaSlider.setValue((int)((initialAlphaSlider.getMaximum()-initialAlphaSlider.getMinimum())*initialAlpha));
    }

    /**
     * Retrieves initialBeta parameter from its corresponding field in the panel
     * @return initialBeta parameter
     */
    protected double get_initialBeta() {
        return Double.parseDouble(initialBetaTextField.getText());
    }

    /**
     * Sets initialBeta parameter into its corresponding field in the panel
     * @param initialBeta initialBeta parameter value to be set
     */
    protected void set_initialBeta(double initialBeta) {
        initialBetaSlider.setValue((int)((initialBetaSlider.getMaximum()-initialBetaSlider.getMinimum())*initialBeta));
    }

    /**
     * Retrieves initialGamma parameter from its corresponding field in the panel
     * @return initialGamma parameter
     */
    protected double get_initialGamma() {
        return Double.parseDouble(initialGammaTextField.getText());
    }

    /**
     * Sets initialGamma parameter into its corresponding field in the panel
     * @param initialGamma initialGamma parameter value to be set
     */
    protected void set_initialGamma(double initialGamma) {
        initialGammaSlider.setValue((int)((initialGammaSlider.getMaximum()-initialGammaSlider.getMinimum())*initialGamma));
    }

    /**
     * Retrieves rsuPercentage parameter from its corresponding field in the panel
     * @return rsuPercentage parameter
     */
    protected double get_rsuPercentage() {
        return Double.parseDouble(rsuPercentageTextField.getText());
    }

    /**
     * Sets rsuPercentage parameter into its corresponding field in the panel
     * @param rsuPercentage rsuPercentage parameter value to be set
     */
    protected void set_rsuPercentage(double rsuPercentage) {
        rsuPercentageSlider.setValue((int)((rsuPercentageSlider.getMaximum()-rsuPercentageSlider.getMinimum())*rsuPercentage));
    }

    /**
     * Retrieves numHopsQueriedRecommenders parameter from its corresponding field in the panel
     * @return numHopsQueriedRecommenders parameter
     */
    protected int get_numHopsQueriedRecommenders() {
        return ((Integer)numHopsQueriedRecommendersSpinner.getValue());
    }

    /**
     * Sets numHopsQueriedRecommenders parameter into its corresponding field in the panel
     * @param numHopsQueriedRecommenders numHopsQueriedRecommenders parameter value to be set
     */
    protected void set_numHopsQueriedRecommenders(int numHopsQueriedRecommenders) {
        numHopsQueriedRecommendersSpinner.setValue(numHopsQueriedRecommenders);
    }

    /**
     * Retrieves notTrustFuzzySetMean parameter from its corresponding field in the panel
     * @return notTrustFuzzySetMean parameter
     */
    protected double get_notTrustFuzzySetMean() {
        return ((double)notTrustFuzzySetMeanSlider.getValue())/(notTrustFuzzySetMeanSlider.getMaximum()-notTrustFuzzySetMeanSlider.getMinimum());
    }

    /**
     * Sets notTrustFuzzySetMean parameter into its corresponding field in the panel
     * @param notTrustFuzzySetMean notTrustFuzzySetMean parameter value to be set
     */
    protected void set_notTrustFuzzySetMean(double notTrustFuzzySetMean) {
        notTrustFuzzySetMeanSlider.setValue((int)((notTrustFuzzySetMeanSlider.getMaximum()-notTrustFuzzySetMeanSlider.getMinimum())*notTrustFuzzySetMean));
    }

    /**
     * Retrieves notTrustFuzzySetStDev parameter from its corresponding field in the panel
     * @return notTrustFuzzySetStDev parameter
     */
    protected double get_notTrustFuzzySetStDev() {
        return ((double)notTrustFuzzySetStDevSlider.getValue())/(notTrustFuzzySetStDevSlider.getMaximum()-notTrustFuzzySetStDevSlider.getMinimum());
    }

    /**
     * Sets notTrustFuzzySetStDev parameter into its corresponding field in the panel
     * @param notTrustFuzzySetStDev notTrustFuzzySetStDev parameter value to be set
     */
    protected void set_notTrustFuzzySetStDev(double notTrustFuzzySetStDev) {
        notTrustFuzzySetStDevSlider.setValue((int)((notTrustFuzzySetStDevSlider.getMaximum()-notTrustFuzzySetStDevSlider.getMinimum())*notTrustFuzzySetStDev));
    }

    /**
     * Retrieves moreOrLessTrustFuzzySetMean parameter from its corresponding field in the panel
     * @return moreOrLessTrustFuzzySetMean parameter
     */
    protected double get_moreOrLessTrustFuzzySetMean() {
        return ((double)moreOrLessTrustFuzzySetMeanSlider.getValue())/(moreOrLessTrustFuzzySetMeanSlider.getMaximum()-moreOrLessTrustFuzzySetMeanSlider.getMinimum());
    }

    /**
     * Sets moreOrLessTrustFuzzySetMean parameter into its corresponding field in the panel
     * @param moreOrLessTrustFuzzySetMean moreOrLessTrustFuzzySetMean parameter value to be set
     */
    protected void set_moreOrLessTrustFuzzySetMean(double moreOrLessTrustFuzzySetMean) {
        moreOrLessTrustFuzzySetMeanSlider.setValue((int)((moreOrLessTrustFuzzySetMeanSlider.getMaximum()-moreOrLessTrustFuzzySetMeanSlider.getMinimum())*moreOrLessTrustFuzzySetMean));
    }

    /**
     * Retrieves moreOrLessTrustFuzzySetStDev parameter from its corresponding field in the panel
     * @return moreOrLessTrustFuzzySetStDev parameter
     */
    protected double get_moreOrLessTrustFuzzySetStDev() {
        return ((double)moreOrLessTrustFuzzySetStDevSlider.getValue())/(moreOrLessTrustFuzzySetStDevSlider.getMaximum()-moreOrLessTrustFuzzySetStDevSlider.getMinimum());
    }

    /**
     * Sets moreOrLessTrustFuzzySetStDev parameter into its corresponding field in the panel
     * @param moreOrLessTrustFuzzySetStDev moreOrLessTrustFuzzySetStDev parameter value to be set
     */
    protected void set_moreOrLessTrustFuzzySetStDev(double moreOrLessTrustFuzzySetStDev) {
        moreOrLessTrustFuzzySetStDevSlider.setValue((int)((moreOrLessTrustFuzzySetStDevSlider.getMaximum()-moreOrLessTrustFuzzySetStDevSlider.getMinimum())*moreOrLessTrustFuzzySetStDev));
    }

    /**
     * Retrieves trustFuzzySetMean parameter from its corresponding field in the panel
     * @return trustFuzzySetMean parameter
     */
    protected double get_trustFuzzySetMean() {
        return ((double)trustFuzzySetMeanSlider.getValue())/(trustFuzzySetMeanSlider.getMaximum()-trustFuzzySetMeanSlider.getMinimum());
    }

    /**
     * Sets trustFuzzySetMean parameter into its corresponding field in the panel
     * @param trustFuzzySetMean trustFuzzySetMean parameter value to be set
     */
    protected void set_trustFuzzySetMean(double trustFuzzySetMean) {
        trustFuzzySetMeanSlider.setValue((int)((trustFuzzySetMeanSlider.getMaximum()-trustFuzzySetMeanSlider.getMinimum())*trustFuzzySetMean));
    }

    /**
     * Retrieves trustFuzzySetStDev parameter from its corresponding field in the panel
     * @return nrustFuzzySetStDev parameter
     */
    protected double get_trustFuzzySetStDev() {
        return ((double)trustFuzzySetStDevSlider.getValue())/(trustFuzzySetStDevSlider.getMaximum()-trustFuzzySetStDevSlider.getMinimum());
    }

    /**
     * Sets trustFuzzySetStDev parameter into its corresponding field in the panel
     * @param trustFuzzySetStDev trustFuzzySetStDev parameter value to be set
     */
    protected void set_trustFuzzySetStDev(double trustFuzzySetStDev) {
        trustFuzzySetStDevSlider.setValue((int)((trustFuzzySetStDevSlider.getMaximum()-trustFuzzySetStDevSlider.getMinimum())*trustFuzzySetStDev));
    }

    @Override
    public TRMParameters get_TRMParameters() {
        TRIP_Parameters tripParameters = new TRIP_Parameters();

        tripParameters.set_initialAlpha(get_initialAlpha());
        tripParameters.set_initialBeta(get_initialBeta());
        tripParameters.set_initialGamma(get_initialGamma());
        tripParameters.set_rsuPercentage(get_rsuPercentage());
        tripParameters.set_numHopsQueriedRecommenders(get_numHopsQueriedRecommenders());
        tripParameters.set_notTrustFuzzySetMean(get_notTrustFuzzySetMean());
        tripParameters.set_notTrustFuzzySetStDev(get_notTrustFuzzySetStDev());
        tripParameters.set_moreOrLessTrustFuzzySetMean(get_moreOrLessTrustFuzzySetMean());
        tripParameters.set_moreOrLessTrustFuzzySetStDev(get_moreOrLessTrustFuzzySetStDev());
        tripParameters.set_trustFuzzySetMean(get_trustFuzzySetMean());
        tripParameters.set_trustFuzzySetStDev(get_trustFuzzySetStDev());

        return tripParameters;
    }

    @Override
    public void set_TRMParameters(TRMParameters trmParameters) {
        TRIP_Parameters tripParameters = (TRIP_Parameters)trmParameters;

        set_initialAlpha(tripParameters.get_initialAlpha());
        set_initialBeta(tripParameters.get_initialBeta());
        set_initialGamma(tripParameters.get_initialGamma());
        set_rsuPercentage(tripParameters.get_rsuPercentage());
        set_numHopsQueriedRecommenders(tripParameters.get_numHopsQueriedRecommenders());
        set_notTrustFuzzySetMean(tripParameters.get_notTrustFuzzySetMean());
        set_notTrustFuzzySetStDev(tripParameters.get_notTrustFuzzySetStDev());
        set_moreOrLessTrustFuzzySetMean(tripParameters.get_moreOrLessTrustFuzzySetMean());
        set_moreOrLessTrustFuzzySetStDev(tripParameters.get_moreOrLessTrustFuzzySetStDev());
        set_trustFuzzySetMean(tripParameters.get_trustFuzzySetMean());
        set_trustFuzzySetStDev(tripParameters.get_trustFuzzySetStDev());

        updateTrustLevelsPanelContainer(trustLevels);
    }

    @Override
    public void setEnabled(boolean enabled) {
        initialAlphaLabel.setEnabled(enabled);
        initialAlphaSlider.setEnabled(enabled);
        initialBetaLabel.setEnabled(enabled);
        initialBetaSlider.setEnabled(enabled);
        initialGammaLabel.setEnabled(enabled);
        initialGammaSlider.setEnabled(enabled);
        rsuPercentageLabel.setEnabled(enabled);
        rsuPercentageSlider.setEnabled(enabled);
        numHopsQueriedRecommendersLabel.setEnabled(enabled);
        numHopsQueriedRecommendersSpinner.setEnabled(enabled);
        notTrustFuzzySetMeanLabel.setEnabled(enabled);
        notTrustFuzzySetMeanSlider.setEnabled(enabled);
        notTrustFuzzySetStDevLabel.setEnabled(enabled);
        notTrustFuzzySetStDevSlider.setEnabled(enabled);
        moreOrLessTrustFuzzySetMeanLabel.setEnabled(enabled);
        moreOrLessTrustFuzzySetMeanSlider.setEnabled(enabled);
        moreOrLessTrustFuzzySetStDevLabel.setEnabled(enabled);
        moreOrLessTrustFuzzySetStDevSlider.setEnabled(enabled);
        trustFuzzySetMeanLabel.setEnabled(enabled);
        trustFuzzySetMeanSlider.setEnabled(enabled);
        trustFuzzySetStDevLabel.setEnabled(enabled);
        trustFuzzySetStDevSlider.setEnabled(enabled);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel initialAlphaLabel;
    private javax.swing.JSlider initialAlphaSlider;
    private javax.swing.JTextField initialAlphaTextField;
    private javax.swing.JLabel initialBetaLabel;
    private javax.swing.JSlider initialBetaSlider;
    private javax.swing.JTextField initialBetaTextField;
    private javax.swing.JLabel initialGammaLabel;
    private javax.swing.JSlider initialGammaSlider;
    private javax.swing.JTextField initialGammaTextField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel moreOrLessTrustFuzzySetMeanLabel;
    private javax.swing.JSlider moreOrLessTrustFuzzySetMeanSlider;
    private javax.swing.JTextField moreOrLessTrustFuzzySetMeanTextField;
    private javax.swing.JLabel moreOrLessTrustFuzzySetStDevLabel;
    private javax.swing.JSlider moreOrLessTrustFuzzySetStDevSlider;
    private javax.swing.JTextField moreOrLessTrustFuzzySetStDevTextField;
    private javax.swing.JLabel notTrustFuzzySetMeanLabel;
    private javax.swing.JSlider notTrustFuzzySetMeanSlider;
    private javax.swing.JTextField notTrustFuzzySetMeanTextField;
    private javax.swing.JLabel notTrustFuzzySetStDevLabel;
    private javax.swing.JSlider notTrustFuzzySetStDevSlider;
    private javax.swing.JTextField notTrustFuzzySetStDevTextField;
    private javax.swing.JLabel numHopsQueriedRecommendersLabel;
    private javax.swing.JSpinner numHopsQueriedRecommendersSpinner;
    private javax.swing.JLabel rsuPercentageLabel;
    private javax.swing.JSlider rsuPercentageSlider;
    private javax.swing.JTextField rsuPercentageTextField;
    private javax.swing.JLabel trustFuzzySetMeanLabel;
    private javax.swing.JSlider trustFuzzySetMeanSlider;
    private javax.swing.JTextField trustFuzzySetMeanTextField;
    private javax.swing.JLabel trustFuzzySetStDevLabel;
    private javax.swing.JSlider trustFuzzySetStDevSlider;
    private javax.swing.JTextField trustFuzzySetStDevTextField;
    private javax.swing.JPanel trustLevelsPanelContainer;
    // End of variables declaration//GEN-END:variables
}